version: '3.4'

services:
    db:
        image: postgres:11
        container_name: db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: gir
        volumes:
            - ./pg/db:/var/lib/postgresql/data_mongo
